### PR TITLE
Rollback version of jasmin-maven-plugin to 1.3.1.6

### PR DESCRIPTION
**Pull request by m4rkmckenna**
Due to 2.X requiring maven 3.1.0

### CODE REVIEW

**Comment by sjcorbett** [comment]
@m4rkmckenna Thanks.

**Comment by ahgittin** [comment]
i see from https://github.com/apache/infrastructure-puppet/blob/deployment/data/ubuntu/1404.yaml that the build machines have maven 3.2.1 installed.  maybe it is simply a question of requesting that version when we build?

**Comment by ahgittin** [comment]
i have changed the build to request maven 3.2.1 so if there is reason we can restore the 2.x jasmine plugin and phantomjs settings in the pom.  @m4rkmckenna @ygy wdyt?

**Comment by sjcorbett** [comment]
@ahgittin How did you change that?

**Comment by m4rkmckenna** [comment]
@ahgittin I'd rather restore 2.X ... best to keep up to date IMO.

**Comment by ahgittin** [comment]
@sjcorbett https://builds.apache.org/job/brooklyn-master-build/configure -- you need a login however.  richard can create one for committers if you need.

**Comment by ahgittin** [comment]
+1 @m4rkmckenna i'll restore that.  btw maven 3.2.1 is available; newest build shows:

```
$ /usr/lib/jvm/java-7-openjdk-amd64//bin/java -Xmx512m -Xms512m -XX:MaxPermSize=512m -cp /home/jenkins/jenkins-slave/maven32-agent.jar:/home/jenkins/jenkins-slave/tools/hudson.tasks.Maven_MavenInstallation/maven-3.2.1/boot/plexus-classworlds-2.5.1.jar:/home/jenkins/jenkins-slave/tools/hudson.tasks.Maven_MavenInstallation/maven-3.2.1/conf/logging jenkins.maven3.agent.Maven32Main /home/jenkins/jenkins-slave/tools/hudson.tasks.Maven_MavenInstallation/maven-3.2.1 /home/jenkins/jenkins-slave/slave.jar /home/jenkins/jenkins-slave/maven32-interceptor.jar /home/jenkins/jenkins-slave/maven3-interceptor-commons.jar 53416
```

**Comment by sjcorbett** [comment]
I can log in but can't configure the build because "sjcorbett is missing the Job/ExtendedRead permission". (I can kick builds off though, thus the one that recently passed on the third attempt!)

**Pull request merged**
