### PR TITLE
Hotfix: Skip the creation of the contains method within Array prototype

### PR DESCRIPTION
**Pull request by tbouron**
This avoids breaking other parts of the UI

### CODE REVIEW

**Comment by neykov** [comment]
Was just about to reply to the email thread :).
The code causing the problem is called only when `loggerEnabled` is true. Suggest disabling logging instead.
Also can't believe they pollyfilled `contains` just to use it a single time on the line following it.

**Comment by tbouron** [comment]
> The code causing the problem is called only when loggerEnabled is true. Suggest disabling logging instead.

Even though, not removing the `contains` is really a big issue. I feel more confortable removing it as it affect every JS arrays.
Again, this is just a temporary fix, I'll look for another autocomplete library after 0.9.0

> Also can't believe they pollyfilled contains just to use it a single time on the line following it.

And yet, it is sadly true... But it's half of my mistake, I choose this library :(

**Comment by neykov** [comment]
My point is that with `loggerEnabled=false` the `Array` prototype will not be patched with `contains`, so no need to delete it.

**Comment by neykov** [comment]
Also I am sure there are bugs in any library we use (as a general principle) :). The question is how long it takes before bumping into them.

**Comment by tbouron** [comment]
> My point is that with loggerEnabled=false the Array prototype will not be patched with contains, so no need to delete it.

My bad, I get what you are saying now. I'll update the PR

**Comment by tbouron** [comment]
@neykov Done

**Comment by neykov** [comment]
The fix works for me, merging.
Thanks @tbouron.

**Pull request merged**
