### PR TITLE
Adding travis config file for an easier build

### PR DESCRIPTION
**Pull request by Numerinico**

### CODE REVIEW

**Comment by m4rkmckenna** [comment]
Hi @Numerinico ... Thanks for the contribution have you signed an ICLA.

Also could you reach out to the mailing list as I believe this change will need to be discussed on there first.  https://brooklyn.apache.org/community/mailing-lists.html

**Comment by Numerinico** [comment]
Hi, thanks for your answer. I just got validated for the ICLA.
I sent a mail to dev-subscribe@brooklyn.apache.org but got no confirmation that I was subscribed.

**Comment by tbouron** [comment]
Hi @Numerinico. I just checked the subscriber list and I cannot see you there. But I'm not entirely sure of the email address you used to subscribe so I might be wrong. Could you send en email to dev-owner@brooklyn.apache.org please? It's a private mail direct to the list moderators, best way to speak to a human. Plus, we will know for sure your email address and will be able to help you more efficiently :)

Just FYI, the subscribe is a double opt-in process so you would know if it worked. Usually, you get a confirmation email instantly after sending an empty email to dev-subscribe@brooklyn.apache.org. Maybe it went down to your spam folder?

**Comment by ahgittin** [comment]
i can see this being useful.  wouldn't mind help @Numerinico maintaining this as and when changes are needed.  merging.

**Pull request merged**
