### PR TITLE
Make absolute paths relative

### PR DESCRIPTION
**Pull request by m4rkmckenna**
Allows you to move the brooklyn-ui from root 

Allows ui to be deployed behind a load balancer or `Web-ContextPath` changed via karaf

### CODE REVIEW

**Comment by tbouron** [comment]
Miss relative path changes into the `<script>` tag at the end of the `index.html` file

**Comment by m4rkmckenna** [comment]
Thanks @tbouron amended

**Comment by tbouron** [comment]
@m4rkmckenna Cannot see the changes

**Comment by m4rkmckenna** [comment]
@tbouron sorry my bad ... forgot how git works

**Comment by tbouron** [comment]
Tested successfully:
- Deployed the war on root `/` => UI is showing up as expected
- Deployed the war on a context path different than root `/` => UI is showing up as expected
- Search for all `/asset` path and checked that they are prefixed by a `.`

LGTM

**Comment by aledsage** [comment]
Thanks @m4rkmckenna @tbouron - merging.

**Pull request merged**
