### PR TITLE
Update to Jasmine 2.X

### PR DESCRIPTION
**Pull request by m4rkmckenna**

### CODE REVIEW

**Comment by ahgittin** [comment]
looks great, merging.  @ygy hopefully this makes it build nicer on ubuntu!

**Comment by sjcorbett** [comment]
Unfortunately jasmine-maven-plugin 2.1 requires Maven 3.1.0+ but the Apache Jenkins server is only on Maven 3.0.4. This causes the build to fail with:
```
Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal com.github.searls:jasmine-maven-plugin:2.1:test (default) on project brooklyn-jsgui: The plugin com.github.searls:jasmine-maven-plugin:2.1 requires Maven version 3.1.0 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
```

**Comment by ahgittin** [comment]
maven 3.1.0 came out nearly 3 years ago so i think we put in a request for that version.

istr there were issues with old build on apache jenkins servers that they couldn't run the old jasmine plugin so not much sense in rolling back.  wdyt @sjcorbett @m4rkmckenna @ygy @aledsage ?

**Comment by sjcorbett** [comment]
A request to upgrade would be sensible. In the meantime it would be good to have Jenkins able to publish snapshots. @m4rkmckenna is using Jasmine 2.x plausible?

**Comment by m4rkmckenna** [comment]
@sjcorbett I havent been able to find a way ... ill have a fix for the above shortly. 

What i find funny is apache maven 3.4 is being built with maven 3.0.5 :smile:

**Comment by m4rkmckenna** [comment]
Opened #14 to address the above

**Pull request merged**
