### PR TITLE
Blueprint Composer cluster field fix

### PR DESCRIPTION
**Pull request by jathanasiou**

### CODE REVIEW

**Review by iuliana — APPROVED** [review]
LGTM

**Review by jcabrerizo — COMMENTED** [review]
LGTM

**Comment by jcabrerizo** [comment]
test this please

**Comment by iuliana** [comment]
The build failure seems unrelated to the change, but I will not merge it without anopther confirmation. 

```
stderr: fatal: unable to access 'https://github.com/apache/brooklyn-ui.git/': Failed to connect to github.com port 443: Connection timed out
```

**Comment by ahgittin** [comment]
this is safe to merge.  merging.

**Pull request closed without merging**
